seed: 114222003020845
run_name: testino
n_dim: 3
n_periodic: 0
delta: 0.0005
dynamic_timestep: true
dynamic_timestep_ramp: 0.0001
n_steps: 10000000
n_steps_equil: 0
boundary: 2
graph_flag: true
auto_graph: true
n_graph: 500
movie_flag: false
zero_temperature: false
system_radius: 15
potential: wca
wca_sig: 1
wca_eps: 1
f_cutoff: 10000
remove_duplicate_interactions: false
coarse_grained_mesh_interactions: false
mesh_coarsening: 2
checkpoint_flag: true
invert_background: false
n_checkpoint: 1000
# br_bead:
#   - name: righties
#     diameter: 1
#     color: 5.3
#     num: 1
#     density: 0.05
#     driving_factor: 1
#     driving_torque: 0.05
#     chiral_handedness: 1
#     draw_type: orientation
#     randomize_handedness: false
#     alignment_torque: 1
#     alignment_interaction: true
#     highlight_handedness: true
#     translational_noise: 0
#     rotational_noise: 0
#     spec_flag: true
#     n_spec: 1000
#     draw_shape: not_a_sphere
#   - name: lefties
#     diameter: 1
#     color: 4.24
#     num: 1
#     density: 0.05
#     driving_factor: 1
#     driving_torque: 0.05
#     chiral_handedness: -1
#     draw_type: orientation
#     randomize_handedness: false
#     alignment_torque: 1
#     alignment_interaction: true
#     highlight_handedness: true
#     translational_noise: 0
#     rotational_noise: 0
#     spec_flag: true
#     n_spec: 1000
#     draw_shape: not_a_sphere
filament:
  - name: spindle
    num: 0
    # partner_destab_A: -0.61550307
    # partner_destab_B: 0.28391844
    # partner_destab_k: 1.3488364
    packing_fraction: -1
    insertion_type: random
    insert_file: examples/assay_3d_insert.yaml
    draw_type: fixed
    color: 2
    diameter: .5
    overlap: false
    length: 10
    min_length: 1
    max_length: 1000
    min_bond_length: 1
    polydispersity_flag: false
    dynamic_instability_flag: true
    persistence_length: 8000 # 2 mm
    driving_factor: 0
    v_poly: 3.1
    v_depoly: 4.05
    f_grow_to_shrink: 0.1
    f_shrink_to_grow: 0.5
    spec_flag: true
    n_spec: 100
    force_induced_catastrophe_flag: true
    fic_factor: 0.001
    spiral_init_flag: false
    spiral_analysis: false
    spiral_number_fail_condition: 0
    friction_ratio: 2
    optical_trap_flag: false
    optical_trap_spring: 20
    optical_trap_fixed: false
    cilia_trap_flag: false
    f_shrink_to_pause: 0.0
    f_pause_to_grow: 0.0
    f_pause_to_shrink: 0.0
    f_grow_to_pause: 0.0
    theta_analysis: false
    lp_analysis: false
    global_order_analysis: false
    perlen_ratio: -1
    drive_from_bond_center: true
    n_equil: 0
    orientation_corr_analysis: false
    orientation_corr_n_steps: 1000
    crossing_analysis: false
    intrinsic_curvature: 0
    flagella_flag: false
    flagella_freq: 1
    flagella_period: 2
    flagella_amplitude: 1
    flocking_analysis: false
    polar_order_analysis: false
    polar_order_n_bins: 100
    polar_order_contact_cutoff: 3
    flock_polar_min: 0.5
    flock_contact_min: 1.5
    highlight_flock: false
    flock_color_ext: 1.57
    flock_color_int: 4.71
    in_out_analysis: false
    nematic_driving: false
    nematic_driving_freq: 0
    peclet_number: -1
    flexure_number: -1
    radius_of_curvature: -1
    intrinsic_curvature_sig: 0
    randomize_intrinsic_curvature_handedness: false
    intrinsic_curvature_min: 0
    highlight_handedness: false
    highlight_curvature: false
    draw_center_of_curvature: false
    error_analysis: false
    polar_order_width: 10
    msd_analysis: false
    curvature_cluster_analysis: false
    cluster_lifetime_min: 100
    cluster_by_handedness: false
    number_fluctuation_analysis: false
    number_fluctuation_boxes: 6
    number_fluctuation_centers: 10
    custom_set_tail: false
    reference_frame_flag: false
chromosome: 
  - name: test
    num: 4
    length: 5
    diameter: 1.5     
    draw_type: fixed
    overlap: false
    zero_temperature: false
    translational_noise: 0.1
    rotational_noise: 1e-6
    color: 3
# crosslink:
#   - name: dynein
#     concentration: .03
#     bind_site_density: 0.4
#     insertion_type: random
#     diameter: 0.5
#     diffusion_s: 0
#     diffusion_d: 0
#     draw_type: fixed
#     color: 4.67
#     energy_dep_factor: 0
#     force_dep_length: 0
#     polar_affinity: 0
#     k_spring: 3000
#     f_stall: 10
#     force_dep_vel_flag: true
#     k_align: 0
#     rest_length: 1
#     step_direction: -1
#     tether_draw_type: fixed
#     tether_diameter: 0.3
#     plus_end_pausing: true
#     minus_end_pausing: false
#     r_capture: 10
#     spec_flag: true
#     n_spec: 100
#     static_flag: false
#     begin_with_bound_crosslinks: 0
#     use_binding_volume: true
#     infinite_reservoir_flag: true
#     k_spring_compress: -1.
#     lut_grid_num: 256
#     tether_color: 4.67