seed: 7859459105545
n_runs: 1
n_random: 1
run_name: sc
n_dim: 3
n_periodic: 0
boundary: 0
system_radius: 100
n_steps: 1000000
i_step: 0
t_step: 0
on_midstep: false
prev_step: 0
delta: 0.001
dynamic_timestep: false
dynamic_timestep_ramp: 0.001
graph_flag: false
n_graph: 1000
graph_diameter: 0
invert_background: false
draw_boundary: true
load_checkpoint: false
checkpoint_run_name: sc
n_load: 0
movie_flag: false
movie_directory: frames
time_analysis: false
bud_height: 680
bud_radius: 300
protrusion_radius: 2
protrusion_length: 80
protrusion_growth_speed: 0
start_protrusion_growth: 0
lj_epsilon: 1
wca_eps: 1
wca_sig: 1
ss_a: 1
ss_rs: 1.5
ss_eps: 1
f_cutoff: 2000
constant_pressure: false
constant_volume: false
target_pressure: 0
target_radius: 100
pressure_time: 100
compressibility: 1
zero_temperature: false
thermo_flag: false
n_thermo: 1000
insert_radius: -1
interaction_flag: true
remove_duplicate_interactions: false
coarse_grained_mesh_interactions: false
mesh_coarsening: 2
species_insertion_failure_threshold: 10000
species_insertion_reattempt_threshold: 10
uniform_crystal: false
n_steps_equil: 0
n_steps_target: 100000
static_particle_number: false
checkpoint_from_spec: false
potential: wca
reflect_at_boundary: false
soft_potential_mag: 10
soft_potential_mag_target: -1
like_like_interactions: true
auto_graph: false
local_order_analysis: false
local_order_width: 50
local_order_bin_width: 0.5
local_order_n_analysis: 100
density_analysis: 0
density_bin_width: 0.1
density_com_only: false
overlap_analysis: false
highlight_overlaps: false
reduced: false
reload_reduce_switch: false
checkpoint_flag: false
n_checkpoint: 10000
knockout_xlink: false
no_midstep: false
single_occupancy: true
turn_off_cell_list: false
species:
  name: species
  num: 0
  diameter: 1
  length: 0
  insertion_type:
